---
- name: 'create hugo container'
  community.docker.docker_compose_v2:
    pull: "always"
    project_name: 'harmonicsoundsystem'
    state: '{{ harmonic_state }}'
    definition:
      networks:
        harmonic_net:
          external: false
      services:
        blog:
          image: 'nginx:latest'
          restart: 'unless-stopped'
          volumes:
            - '{{ harmonic_docker_host_dir }}/data/public:/usr/share/nginx/html:ro'
          networks:
            - 'harmonic_net'
          ports:
            - '{{ harmonic_port }}:80'
...
