---
- name: "Create base folder"
  ansible.builtin.file:
    path: "{{ harmonic_page_base_dir }}/{{ item }}"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0755"
  loop:
    - "public"
    - "docker"
  tags:
    - "harmonic:build"

- name: "Copy Dockerfile build files"
  ansible.builtin.copy:
    src: "files/{{ item.src }}"
    dest: "{{ harmonic_page_base_dir }}/docker/{{ item.dest | default(item.src) }}"
    owner: "root"
    group: "root"
    mode: "{{ item.mode | default('0644') }}"
  loop:
    - {"src": "Dockerfile"}
    - {"src": "entrypoint.sh"}
  tags:
    - "harmonic:build"

- name: "Build hugo build image"
  community.docker.docker_image:
    name: "dhoessl/hugo"
    source: "build"
    build:
      path: "{{ harmonic_page_base_dir }}/docker"
      pull: true
  tags:
    - "harmonic:build"

- name: "Start container to create new public"
  community.docker.docker_container:
    name: "harmonic_hugo"
    image: "dhoessl/hugo"
    auto_remove: true
    volumes:
      - "{{ harmonic_page_base_dir }}/public:/public"
  tags:
    - "harmonic:run"
...
