---
- name: 'import prepare_filesystem task'
  import_tasks: 'prepare_filesystem.yaml'
  tags:
    - 'harmonic:filesystem'

- name: 'import create_container task'
  import_tasks: 'create_container.yaml'
  tags:
    - 'harmonic:docker'
...
