---
title: 'Harmonic Soundsystem'
baseURL: 'https://www.harmonicsoundsystem.de/'
theme: [ 'Arcana' ]

enableRobotsTXT: true

# SectionPagesMenu: 'main'
pagination:
  pagerSize: 10

defaultContentLanguage: 'de'
defaultContentLanguageInSubdir: true

languages:
  de:
    title: 'Harmonic Soundsystem'
    contentDir: 'content/german'
    languageName: 'Deutsch'
    languageCode: 'de-de'
    weight: 1
  en:
    title: 'Harmonic Soundsystem'
    contentDir: 'content/english'
    languageName: 'English'
    languageCode: 'en-US'
    weight: 2

sitemap:
  changefreq: 'monthly'
  priority: 0.5
  filename: 'sitemap.xml'

params:
  env: 'production'
  description: 'Harmonic Soundsystem'
  images:
    - "images/harmonic_logo_with_sound.jpg"
  show_post_dates: false
  keywords: []
  author: 'harmonicsoundsystem'
  date_format: ':date_long'
  background_color_class: 'bg-black'
  recent_posts_number: 3
  favicon: 'images/fav/fav.ico'
  text_color: ''
  site_logo: 'images/fav/small_fav.ico'
  social:
    - title: "Facebook"
      icon: "fa-facebook-f"
      url: "https://www.facebook.com/harmonicsoundsystem"
    - title: "Instagram"
      icon: "fa-instagram"
      url: "https://www.instagram.com/harmonic_soundsystem/"
  enableSourceMaps: true

outputs:
  home:
    - 'HTML'
    - 'RSS'
    # - 'JSON'
...
